# **Numpy**

Numpy es una librería de Python que se utiliza para:
- Realizar cálculos numéricos eficientes
- Manejar y operar con arrays multidimensionales

### **Ventajas:**

- **Velocidad**: Es más rápido que usar listas nativas de Python, ya que está optimizado para cálculos numéricos.
- **Tamaño**: Optimiza bien el almacenamiento en memoria, permitiendo manejar grandes volúmenes de datos de manera eficiente.
- **Tipos de datos**: Maneja varios tipos de datos, incluyendo enteros, flotantes, complejos, y booleanos.
- **Operaciones vectorizadas**: Permite realizar operaciones matemáticas en arrays completos sin necesidad de bucles explícitos.
- **Funciones matemáticas**: Ofrece una amplia gama de funciones matemáticas y estadísticas.
- **Compatibilidad**: Se integra fácilmente con otras librerías como Pandas, Matplotlib y Scipy.

___

### **¿Como importar NumPy?**

In [9]:
import numpy as np

___

### **El Array en NumPy**

Un array es una estructura de datos que almacena una colección de elementos.

Se crea de la siguiente manera:

In [2]:
array = np.array([1, 2, 3, 4, 5])
print(array)
type(array)

[1 2 3 4 5]


numpy.ndarray

Como se puede observar, el tipo de dato que usa NumPy para sus arrays es **ndarray**, que es la abreviatura de **N-dimensional array**, o **array multidimensional** en español.

___

### **Características principales**

####  **1. Multidimensionalidad**

Un **ndarray** puede ser un array de cualquier número de dimensiones.

**- Escalares**

In [4]:
scalar = np.array(5)
print(scalar)

5


**- Vectores (1D)**

In [13]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


**- Matrices (2D)**

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**- Tensores (3D)**

In [15]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


---

#### **2. Indexación**

Cada elemento del ndarray está indexado comenzando desde 0, y podemos acceder fácilmente a ellos utilizando su índice.

In [58]:
array = np.array([3, 1, 4, 8, 2])
print(array[0])
print(array[1] + array[3])
print("")

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0]) # Se imprime la primera fila
print(matrix[:, 0]) # Se imprime la primera columna
print(matrix[1][2]) # Se imprime el elemento de la segunda fila y tercera columna

3
9

[1 2 3]
[1 4 7]
6


#### **Slicing**
Es una técnica que te permite acceder y modificar sub-secciones (subarrays) de un array. La sintaxis básica para hacer slicing en un array de NumPy es la siguiente:

**array[inicio:fin:paso]**

In [59]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Elementos del índice 2 al 5 (sin incluir 5):", array[2:5])
print("Elementos del índice 0 al 8 con paso 2:", array[0:8:2])

Elementos del índice 2 al 5 (sin incluir 5): [30 40 50]
Elementos del índice 0 al 8 con paso 2: [10 30 50 70]


---

####  **2. Homogeneidad**

Todos los elementos dentro de un **ndarray** son del mismo tipo de dato.



In [66]:
#Array de Python
lista = [1, 2.5, "hello"]
print("Lista de Python:", lista)
print("Tipos de los elementos en el array de python:")
for i, elem in enumerate(lista):
    print(f"Elemento {i}: {type(elem)}")

Lista de Python: [1, 2.5, 'hello']
Tipos de los elementos en el array de python:
Elemento 0: <class 'int'>
Elemento 1: <class 'float'>
Elemento 2: <class 'str'>


In [67]:
# Array de NumPy
array = np.array([1, 2.5, "hello"])
print("Array de NumPy:", array)


print("Tipo de los elementos en el array de NumPy:")
print(array.dtype)  # Tipo de dato común para todos los elementos

Array de NumPy: ['1' '2.5' 'hello']
Tipo de los elementos en el array de NumPy:
<U32


---

####  **3. Eficiencia**

Los arrays **ndarray** están implementados en **C**, lo que permite que las operaciones sean mucho más rápidas que las realizadas sobre listas tradicionales de Python

In [37]:
import time

# Lista de Python con un millón de elementos
lista_python = list(range(1, 1000001))

# Array de NumPy con un millón de elementos
array_numpy = np.array(range(1, 1000001))

# Medir el tiempo de suma de la lista de Python
start_time = time.time()
sum(lista_python)
print("Tiempo para sumar la lista de Python:", time.time() - start_time)

# Medir el tiempo de suma del array de NumPy
start_time = time.time()
np.sum(array_numpy)
print("Tiempo para sumar el array de NumPy:", time.time() - start_time)

Tiempo para sumar la lista de Python: 0.012794733047485352
Tiempo para sumar el array de NumPy: 0.0010662078857421875


---

####  **4. Soporte para operaciones vectorizadas**

Los arrays **ndarray** permiten realizar operaciones matemáticas de manera eficiente y directa sobre todos los elementos del array sin necesidad de usar bucles explícitos.

In [43]:
array = np.array([1, 2, 3, 4, 5])

# Operaciones vectorizadas en el array
multiplicado_por_2 = array * 2
sumado_3 = array + 3
raiz_cuadrada = np.sqrt(array)

# Imprimir los resultados
print("Array original:", array)
print("Array multiplicado por 2:", multiplicado_por_2)
print("Array sumado 3:", sumado_3)
print("Raíz cuadrada de cada elemento:", raiz_cuadrada)

Array original: [1 2 3 4 5]
Array multiplicado por 2: [ 2  4  6  8 10]
Array sumado 3: [4 5 6 7 8]
Raíz cuadrada de cada elemento: [1.         1.41421356 1.73205081 2.         2.23606798]


---

## **Atributos**

El **ndarray** tiene varios atributos útiles como:

In [11]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix)
print("\nAtributos")
print("Dimension:", matrix.ndim)  # Devuelve el número de dimensiones.
print("Número de elementos por dimension:", matrix.shape)  # Devuelve una tupla con el número de elementos en cada dimensión.
print("Número de elementos totales:", matrix.size)   # Devuelve el número total de elementos.
print("Tipo de datos:", matrix.dtype)  # El tipo de datos de los elementos en el array.
print("Tamaño de los elementos:", matrix.itemsize)  # El tamaño en bytes de cada elemento.

[[1 2]
 [3 4]
 [5 6]]

Atributos
Dimension: 2
Número de elementos por dimension: (3, 2)
Número de elementos totales: 6
Tipo de datos: int64
Tamaño de los elementos: 8


Puedes cambiar el tipo de datos modificando el atributo **dtype**, así:

In [83]:
array = np.array([0, 1, 2, 0], dtype=np.float64)
print(array)
print(array.dtype)

[0. 1. 2. 0.]
float64


O puedes cambiar el tipo de datos de un array existente así:

In [84]:
array = array.astype(np.bool)
array

array([False,  True,  True, False])

In [85]:
array = array.astype(np.int_)
array = array.astype(np.str_)
array

array(['0', '1', '1', '0'], dtype='<U21')

___

### **Expandir dimensiones**
Puedes expandir la dimension de un array usando **np.expand_dims()**.

- **axis=0** para agregar filas

In [11]:
array = np.array([2,4,6])
print(array)
array.ndim

[2 4 6]


1

In [4]:
array_expand = np.expand_dims(array, axis=0)
print(array_expand)
print(array_expand.shape)
array_expand.ndim

[[2 4 6]]
(1, 3)


2

- **axis=1** para agregar columnas

In [13]:
array_expand_2 = np.expand_dims(array, axis=1)
print(array_expand_2)
print(array_expand_2.shape)
array_expand_2.ndim

[[2]
 [4]
 [6]]
(3, 1)


2

___

### **Reducir dimensiones**
Cuando tienes un array con dimensiones adicionales o no deseadas, puedes usar el método **np.squeeze()** para eliminar cualquier dimensión de tamaño 1. Esto es útil para simplificar la estructura del array y facilitar su manipulación.

In [6]:
array = np.array([1, 2, 3], ndmin=5)
print(array, array.ndim)

[[[[[1 2 3]]]]] 5


In [7]:
reduced_array = np.squeeze(array)
print(reduced_array, reduced_array.ndim)

[1 2 3] 1


___

## **Autorellenar un array**

### **Elementos ordenados**

Para crear un array con valores espaciados uniformemente dentro de un rango especificado, puedes usar la función **np.arange()**.

- Crear un rango básico

In [ ]:
array = np.arange(10) # Array de 0 a 10
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Especificar un valor inicial

In [21]:
array = np.arange(5,15) # Array con rango de 5 a 15
array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- Usar un paso específico

In [20]:
array = np.arange(1, 10, 2)  # Rango de 1 a 10 con un paso de 2
array

array([1, 3, 5, 7, 9])

- Especificar un tipo de dato

In [22]:
arr = np.arange(1, 5, dtype=float)  # Crea un rango con tipo float
print(arr)

[1. 2. 3. 4.]


___

### **Elementos distribuidos**
Con la función **np.linespace()** puedes generar una secuencia de números igualmente espaciados dentro de un rango definido.

**Usos comunes:**
- Generación de puntos para gráficos y visualizaciones
- Interpolación y ajuste de curvas
- Simulaciones numéricas

In [34]:
arr = np.linspace(0, 5, num=10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

___

### **Arrays de ceros (0)**
En muchas ocasiones, necesitarás inicializar arrays para almacenar resultados posteriormente. Para crear un array lleno de ceros, se utiliza la función **np.zeros()**.

- Crear un arreglo unidimensional de ceros

In [23]:
arr = np.zeros(5)  # Crea un arreglo de 5 ceros
print(arr)

[0. 0. 0. 0. 0.]


- Crear una matriz de ceros

In [24]:
arr = np.zeros((3, 4))  # Matriz de 3 filas y 4 columnas
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- Especificar el tipo de datos

In [25]:
arr = np.zeros(5, dtype=int)  # Arreglo de 5 ceros enteros
print(arr)

[0 0 0 0 0]


___

### **Arrays de unos (1)**

Tambíen puedes llenar arrays con unos (1) usando **np.ones()**, que tiene la misma estructura y funcionalidades de **np.zeros()**.

In [28]:
arr_ones = np.ones((3,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

___

### **Matriz identidad**
La función **np.eye()** se utiliza para generar una matriz identidad, que es una matriz cuadrada donde los elementos de la diagonal principal son unos, mientras que el resto de los elementos son ceros.

In [43]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

___

### **Array random**
También se puede generar valores aleatorio en un array usando **np.random.rand()**. Esta función crea valores aleatorios entre 0 y 1.

In [44]:
random_arr = np.random.rand(3, 2)
random_arr

array([[0.93205498, 0.15826316],
       [0.84281975, 0.35010304],
       [0.47603377, 0.67473685]])

Si necesitas que los valores aleatorios estén dentro de un rango utiliza **np.random.randint()**.

In [46]:
random_arr = np.random.randint(1, 10, size=(3, 2))
random_arr

array([[5, 3],
       [7, 1],
       [4, 8]])

___

### **Redimensionar un array**
La función **np.reshape()** permite cambiar la dimension del array, siempre y cuando el número total de elementos sea el mismo antes y después del cambio.

In [67]:
arr = np.random.randint(0,10, size=(2, 4))
arr

array([[0, 9, 5, 8],
       [5, 1, 4, 2]])

In [68]:
arr_reshape = arr.reshape(1,8)
arr_reshape

array([[0, 9, 5, 8, 5, 1, 4, 2]])

Para el control del orden de los elementos al hacer el redimensionamiento se puede usar el argumento **order**, que puede tomar los siguientes valores:

- **'C' (por defecto):** Los datos se leen en orden de fila (C-style row-major order).

In [69]:
arr_reshape_c = arr.reshape(4,2, order='C')
arr_reshape_c

array([[0, 9],
       [5, 8],
       [5, 1],
       [4, 2]])

- **'F':** Los datos se leen en orden de columna (Fortran-style column-major order).

In [71]:
arr_reshape_f = arr.reshape(4,2, order='F')
arr_reshape_f

array([[0, 5],
       [5, 4],
       [9, 8],
       [1, 2]])

- **'A':** Adapta el comportamiento según el diseño de memoria del arreglo original: actúa como 'C' si está en orden 'C', y como 'F' si está en orden 'F'.

In [74]:
arr_reshape_a = arr_reshape_f.reshape(4,2, order='A')
arr_reshape_a # Va a ser order 'F' porque el array original fue creado con order 'F'

array([[0, 5],
       [5, 4],
       [9, 8],
       [1, 2]])

___